# Generated by Django 4.0.2 on 2022-02-06 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('date', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
    ]
